WebApplication/Models/ErrorViewModel.cs
using System;

namespace WebApplication.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplication/Models/ItemDoPedidoViewModel.cs
using Dominio.Enums;
using System;

namespace WebApplication.Models
{
    public class ItemDoPedidoViewModel
    {
        public Guid Id { get; set; }
        public int Quantidade { get; set;  }
        public decimal ValorUnitario { get; set; }
        public decimal SubTotal { get; set; }
        public EStatusItem StatusItem { get; set; }
    }
}

WebApplication/Models/MesaViewModel.cs
using Dominio.Enums;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication.Models
{
    public class MesaViewModel
    {
        public MesaViewModel()
        {
            Data = DateTime.Now;
            Cliente = "Consumidor";
        }

        [HiddenInput]
        public Guid Id { get; set; }

        [Required(ErrorMessage = "*Campo Obrigatório!!!")]
        public int Numero { get; set; }

        [Required(ErrorMessage = "*Campo Obrigatório!!!")]
        public string Cliente { get; set; }

        [DataType(DataType.Date)]
        public DateTime Data { get; set; }

        [Required(ErrorMessage = "*Campo Obrigatório!!!")]
        public EStatusMesa Status { get; set; }

    }
}

WebApplication/Models/PedidoViewModel.cs
using Dominio.Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication.Models
{
    public class PedidoViewModel
    {
        public Guid Id {  get; set; }
        public DateTime DatadoPedido { get; set; }
        public decimal ValorTotal { get; set; }
        public EStatusPedido StatusPedido { get; set; }
        public int QuantidadeDeItens { get; set; }
    }
}

WebApplication/Models/ProdutoViewModel.cs
using Dominio.Enums;
using System;

namespace WebApplication.Models
{
    public class ProdutoViewModel
    {
        public Guid Id {  get; set; }
        public string Descricao { get; set; }
        public decimal PrecoCompra { get; set; }
        public decimal PrecoVenda { get; set; }
        public int QtdeEstoque { get; set; }
        public DateTime DataCadastro { get; set; }
        public EStatusProduto EstatusProduto { get; set; }
    }
}

WebApplication/Controllers/HomeController.cs
using Dominio.IRepositories;
using Historia.Mesas;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WebApplication.Factories;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        private readonly ConsultarMesa _consultarMesa;

        public HomeController(ILogger<HomeController> logger, IMesaRepository mesaRepository)
        {
            _logger = logger;
            _consultarMesa = new ConsultarMesa(mesaRepository);
        }

        public async Task<IActionResult> Index()
        {
            var listaMesas = await _consultarMesa.BuscarTodos();
            var ListarMesasViewModel = MesaFactory.MapearListaMesaViewModel(listaMesas);

            return View(ListarMesasViewModel);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplication/Controllers/MesaController.cs
using Dominio.IRepositories;
using Historia.Mesas;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;
using WebApplication.Factories;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    public class MesaController : Controller
    {
        private readonly AdicionarMesa _adicionarMesa;
        private readonly AlterarMesa _alterarMesa;
        private readonly ConsultarMesa _consultarMesa;
        private readonly DeletarMesa _deletarMesa;

        public MesaController(IMesaRepository mesaRepository)
        {
            _adicionarMesa = new AdicionarMesa(mesaRepository);
            _alterarMesa = new AlterarMesa(mesaRepository);
            _consultarMesa = new ConsultarMesa(mesaRepository);
            _deletarMesa = new DeletarMesa(mesaRepository);

        }

        public async Task<IActionResult> Index()
        {
            var listaMesas = await _consultarMesa.BuscarTodos();
            var ListarMesasViewModel = MesaFactory.MapearListaMesaViewModel(listaMesas);

            return View(ListarMesasViewModel);
        }

        public IActionResult Adicionar()
        {
            MesaViewModel mesa = new MesaViewModel();
            return PartialView("_AdicionarMesa", mesa);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Adicionar(MesaViewModel mesaViewModel)
        {
            if (ModelState.IsValid)
            {
                var mesa = MesaFactory.MapearMesa(mesaViewModel);

                await _adicionarMesa.Executar(mesa);

                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Alterar(Guid id)
        {
            var mesa = await _consultarMesa.BuscarPorId(id);

            if (mesa == null)
            {
                return RedirectToAction("Index");
            }

            var mesaViewModel = MesaFactory.MapearMesaViewModel(mesa);

            return PartialView("_AlterarMesa", mesaViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Alterar(Guid id, MesaViewModel mesaViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(mesaViewModel);
            }

            var mesa = MesaFactory.MapearMesa(mesaViewModel);

            await _alterarMesa.Executar(id, mesa);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Detalhar(Guid id)
        {
            var mesa = await _consultarMesa.BuscarPorId(id);

            if (mesa == null)
            {
                return RedirectToAction("Index");
            }

            var mesaViewModel = MesaFactory.MapearMesaViewModel(mesa);

            return PartialView("_DetalhesDaMesa", mesaViewModel);
        }

        public async Task<IActionResult> Deletar(Guid id)
        {
            var mesa = await _consultarMesa.BuscarPorId(id);

            if (mesa == null)
            {
                return RedirectToAction("Index");
            }

            await _deletarMesa.Executar(mesa);

            return RedirectToAction("Index");
        }
    }
}

WebApplication/Views/Cliente/Adicionar.cshtml
@model WebApplication.Models.ClienteViewModel

@{
    ViewData["Title"] = "Adicionar";
}

<h1>Adicionar</h1>

<h4>Novo Cliente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Adicionar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="HoraChegada" class="control-label"></label>
                <input asp-for="HoraChegada" class="form-control" />
                <span asp-validation-for="HoraChegada" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HoraSaida" class="control-label"></label>
                <input asp-for="HoraSaida" class="form-control" />
                <span asp-validation-for="HoraSaida" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication/Views/Cliente/Alterar.cshtml
@model WebApplication.Models.ClienteViewModel

@{
    ViewData["Title"] = "Alterar";
}

<h1>Alterar</h1>

<h4>Alterar Cliente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Alterar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MesaId" class="control-label"></label>
                <input asp-for="MesaId" class="form-control" />
                <span asp-validation-for="MesaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HoraChegada" class="control-label"></label>
                <input asp-for="HoraChegada" class="form-control" />
                <span asp-validation-for="HoraChegada" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HoraSaida" class="control-label"></label>
                <input asp-for="HoraSaida" class="form-control" />
                <span asp-validation-for="HoraSaida" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication/Views/Cliente/Detalhar.cshtml
@model WebApplication.Models.ClienteViewModel

@{
    ViewData["Title"] = "Detalhar";
}

<h1>Detalhar</h1>

<div>
    <h4>Detalhes de Cliente</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MesaId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MesaId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HoraChegada)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HoraChegada)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HoraSaida)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HoraSaida)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Alterar", "Alterar", new {  id = Model.Id  }) |
    <a asp-action="Index">Voltar</a>
</div>

WebApplication/Views/Cliente/Index.cshtml
@model IEnumerable<WebApplication.Models.ClienteViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Adicionar">Adicionar Novo Cliente</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MesaId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HoraChegada)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HoraSaida)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MesaId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HoraChegada)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HoraSaida)
            </td>
            <td>
                @Html.ActionLink("Alterar", "Alterar", new {  id=item.Id }) |
                @Html.ActionLink("Detalhar", "Detalhar", new { id=item.Id }) |
                @Html.ActionLink("Deletar", "Deletar", new { id=item.Id })
            </td>
        </tr>
}
    </tbody>
</table>

WebApplication/Views/Home/Index.cshtml
@model IEnumerable<WebApplication.Models.MesaViewModel>

@{
    ViewData["Title"] = "Página Principal";
}

<section>
    <div class="row container-lista">
        @foreach (var mesa in Model)
        {
            <a class="lista-item"  asp-controller="Mesa" asp-action="Detalhar" asp-route-id="@mesa.Id">
                <div>
                    <div class="text-center">
                        <h4>Mesa<br /></h4>
                        <p class="titulo-card "><strong>@Html.DisplayFor(modelItem => mesa.Numero)</strong></p>
                    </div>
                    <p class="status-card-aberta">@Html.DisplayFor(x => mesa.Status)</p>
                </div>
            </a>
        }
    </div>

</section>

WebApplication/Views/Mesa/Index.cshtml
@model IEnumerable<WebApplication.Models.MesaViewModel>

@{
    ViewData["Title"] = "Index";
}

<div id="PlaceHolderHere"></div>

<button type="button" class="btn btn-info" data-toggle="ajax-modal" data-target="#myModal" data-url="@Url.Action("Adicionar")">Adicionar Mesa</button>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Numero)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Data)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cliente)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model) 
        {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Numero)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Data)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Status)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Cliente)
                    </td>
                    <td>
                        <button type="button" class="btn btn-info" data-toggle="ajax-modal" data-target="#myModal" data-url="@Url.Action($"Alterar/{item.Id}")">Alterar</button>
                        <button type="button" class="btn btn-info" data-toggle="ajax-modal" data-target="#myModal" data-url="@Url.Action($"Detalhar/{item.Id}")">Detalhes</button>
                        @Html.ActionLink("Deletar", "Deletar", new {  id=item.Id  } , new { @class = "btn btn-outline-danger", @onClick = "javascript:return" + " confirm('Confirma a Exclusão?')" })
                    </td>
                </tr>
        }
    </tbody>
</table>

WebApplication/Views/Mesa/_AdicionarMesa.cshtml
@model MesaViewModel

<div class="modal fade" id="myModal">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
       <div class="modal-header">
            <h2 class="modal-title" id="myModalLabel">Adicionar Nova Mesa</h2>
            <button type="button" class="close" data-dismiss="modal">
                <span>x</span>
            </button>
        </div>
        <div class="modal-body">
            <form asp-action="Adicionar">
                 <div class="form-group">
                     <label asp-for="Data" class="control-label">@Model.Data</label>
                </div>
                <div class="form-group">
                    <label asp-for="Numero" class="control-label"></label>
                    <input asp-for="Numero" class="form-control" />
                    <span asp-validation-for="Numero" class="text-danger"></span>
                </div>    
                <div class="form-group">
                      <label asp-for="Status" class="control-label"></label>
                      <input asp-for="Status" class="form-control" />
                      <span asp-validation-for="Status" class="text-danger"></span>
                </div>
                <div class="form-group">
                      <label asp-for="Cliente" class="control-label"></label>
                      <input asp-for="Cliente" class="form-control" />
                      <span asp-validation-for="Cliente" class="text-danger"></span>
                </div>
                <div class="modal-footer">
                      <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Cancelar</button>
                      <button type="submit" class="btn btn-outline-success">Salvar</button>
                </div>
            </form>     
        </div>
    </div>
  </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
 

WebApplication/Views/Mesa/_AlterarMesa.cshtml
@model MesaViewModel

<div class="modal fade" id="myModal">
  <div class="modal-dialog">
    <div class="modal-content">
       <div class="modal-header">
            <h2 class="modal-title" id="myModalLabel">Adicionar Nova Mesa</h2>
            <button type="button" class="close" data-dismiss="modal">
                <span>x</span>
            </button>
        </div>
        <div class="modal-body">
            <form asp-action="Alterar">
                    <div class="form-group">
                        <input type="hidden" asp-for="@Model.Id"/>
                        <label asp-for="Numero" class="control-label"></label>
                        <input asp-for="Numero" class="form-control" />
                        <span asp-validation-for="Numero" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Cliente" class="control-label"></label>
                        <input asp-for="Cliente" class="form-control" />
                        <span asp-validation-for="Cliente" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Status" class="control-label"></label>
                        <input asp-for="Status" class="form-control" />
                        <span asp-validation-for="Status" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Data" class="control-label"></label>
                        <input asp-for="Data" class="form-control" />
                        <span asp-validation-for="Data" class="text-danger"></span>
                    </div>
            </form>     
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
            <button type="submit" class="btn btn-success" data-save="modal">Salvar Alteração</button>
        </div>
    </div>
  </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
 

WebApplication/Views/Mesa/_DetalhesDaMesa.cshtml
@model MesaViewModel

<div class="modal fade" id="myModal">
  <div class="modal-dialog">
    <div class="modal-content">
       <div class="modal-header">
            <h2 class="modal-title" id="myModalLabel">Adicionar Nova Mesa</h2>
            <button type="button" class="close" data-dismiss="modal">
                <span>x</span>
            </button>
        </div>
        <div class="modal-body">
            <form>
                <dl class="row">
                    <dt class = "col-sm-2">
                        @Html.DisplayNameFor(model => model.Id)
                    </dt>
                    <dd class = "col-sm-10">
                        @Html.DisplayFor(model => model.Id)
                    </dd>
                    <dt class = "col-sm-2">
                        @Html.DisplayNameFor(model => model.Numero)
                    </dt>
                    <dd class = "col-sm-10">
                        @Html.DisplayFor(model => model.Numero)
                    </dd>
                    <dt class = "col-sm-2">
                        @Html.DisplayNameFor(model => model.Cliente)
                    </dt>
                    <dd class = "col-sm-10">
                        @Html.DisplayFor(model => model.Cliente)
                    </dd>
                    <dt class = "col-sm-2">
                        @Html.DisplayNameFor(model => model.Status)
                    </dt>
                    <dd class = "col-sm-10">
                        @Html.DisplayFor(model => model.Status)
                    </dd>
                    <dt class = "col-sm-2">
                        @Html.DisplayNameFor(model => model.Data)
                    </dt>
                    <dd class = "col-sm-10">
                        @Html.DisplayFor(model => model.Data)
                    </dd>
                </dl>
            </form>     
        </div>
    </div>
  </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
 

WebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Prato da Casa</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body id="body-pd">
    <div class="navbar-1" id="navbar">
        <nav class="nav">
            <div>
                <div class="nav__brand">
                    <ion-icon name="menu-outline" class="nav__toggle" id="nav-toggle"></ion-icon>
                    <h6 href="#" class="nav__logo">Prato da Casa</h6>
                </div>
                <div class="nav__list">
                    <a asp-controller="Home" asp-action="Index" class="nav__link">
                        <ion-icon name="home-outline" class="nav__icon"></ion-icon>
                        <span class="nav__name">Salão</span>
                    </a>

                    <a asp-controller="Mesa"  asp-action="Index" class="nav__link">
                        <ion-icon name="tablet-landscape-outline" class="nav__icon"></ion-icon>
                        <span class="nav__name">Mesas</span>
                    </a>
                    <a href="#" class="nav__link">
                        <ion-icon name="grid-outline" class="nav__icon"></ion-icon>
                        <span class="nav__name">Cardápio</span>
                    </a>
                    <a href="#" class="nav__link">
                        <ion-icon name="call-outline" class="nav__icon"></ion-icon>
                        <span class="nav__name">Contatos</span>
                    </a>
                </div>
            </div>

            <a href="#" class="nav__link">
                <ion-icon name="log-out-outline" class="nav__icon"></ion-icon>
                <span class="nav__name">Logout</span>
            </a>

        </nav>
    </div>

    <main class="container">
        @RenderBody()
    </main>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>